### ISSUE TITLE
RuntimeError: Cannot find a block for ID: SchmidlCox

### ISSUE THREAD

**Issue by dadopap** [EttusResearch/gr-ettus#13]
I am trying to use RFNoC:OFDM sync block, qith the fpga image usrp_x310_fpga_RFNOC_XG.bit downloaded using the python script.

I have the ettus X310.
The problem is that when I run the grc, I get the following error:
RuntimeError: Cannot find a block for ID: SchmidlCox

Are the OFDM RFNoC blocks included in the fpga image?
If so, how can I solve my problem?

Thanks

**Comment by natetemple** [comment]
@dadopap The SchmidlCox block is not included with the FPGA image, you should build your own image with that block included using the uhd_image_builder scripts. I'm going to close this issue, if you have any more questions, please email us at support@ettus.com
