### ISSUE TITLE
Rfnoc tutorial issue 

### ISSUE THREAD

**Issue by idanhauser** [EttusResearch/gr-ettus#16]
Hello, I'm doing this tutorial and I used the YouTube video of it.. 
 I'm really at the end of this tutorial.. But after I finished everything and I run my application on gnuradio i have these errors 👍

> file "~/rfnoc-tutorial/examples/rfnoc_mygain. Py" , line 325,in <module> main() 
> file "~/rfnoc-tutorial/examples/rfnoc_mygain. Py" , line 313,in main tb=top_block_cls() 
> file "~/rfnoc-tutorial/examples/rfnoc_mygain. Py" , line 129,in __init__ attributeError:'module' object has no attribute 'gain' 

what have i done wrong?  I did exactly as this guide.. 
Thank you so much 
Idan

**Comment by neelpandeya** [comment]
Hello Idan:

This issue is not specific to gr-ettus, and GitHub Issues is not the best place to report these kind of problems. Could you please send an email to `support@ettus.com` instead? We'll be happy to help you from there. Thanks.

**Comment by 1030677119** [comment]
> Hello, I'm doing this tutorial and I used the YouTube video of it..
> I'm really at the end of this tutorial.. But after I finished everything and I run my application on gnuradio i have these errors 👍
> 
> > file "~/rfnoc-tutorial/examples/rfnoc_mygain. Py" , line 325,in  main()
> > file "~/rfnoc-tutorial/examples/rfnoc_mygain. Py" , line 313,in main tb=top_block_cls()
> > file "~/rfnoc-tutorial/examples/rfnoc_mygain. Py" , line 129,in **init** attributeError:'module' object has no attribute 'gain'
> 
> what have i done wrong? I did exactly as this guide..
> Thank you so much
> Idan

Hello @idanhauser 
I'm facing the same issue, have you fixed this?  If so, how you fixed this?
Thanks!
Matt
