### ISSUE TITLE
No file 

### ISSUE THREAD

**Issue by yuanhaowang1213** [EttusResearch/gr-ettus#23]
When I was installing, the error came 'uhd/rfnoc/window_block_ctrl.hpp: No such file or directory
compilation terminated' and 'uhd/rfnoc/fir_block_ctrl.hpp: No such file or directory
compilation terminated.' It seems that in the uhd repository, you did not upload the window_block_ctrl.hpp and fir_block_ctrl.hpp. I could not find these two files anywhere.

**Comment by primercuervo** [comment]
@yuanhaowang1213 the files that you mention are listed as expected here https://github.com/EttusResearch/uhd/tree/rfnoc-devel/host/include/uhd/rfnoc

Please be sure that your UHD is in the rfnoc-devel branch.

**Comment by yuanhaowang1213** [comment]
@primercuervo Yeah, I found it, thank you. But I cannot get it from git clone command.

**Comment by primercuervo** [comment]
@yuanhaowang1213 FYI: 

from the cloning stage:

    $ git clone https://github.com/EttusResearch/uhd.git -b rfnoc-devel

after cloning:

    $ git clone https://github.com/EttusResearch/uhd.git 
    $ cd uhd
    $ git checkout rfnoc-devel

Given that you already found your files, we will close this issue. Keep in mind that RFNoC is fully supported only in the rfnoc-devel branch.
