### ISSUE TITLE
‘get_system_time’ is not a member of ‘uhd::time_spec_t’

### ISSUE THREAD

**Issue by yuanhaowang1213** [EttusResearch/gr-ettus#24]
When I compile the gr-ettus. An error occurs that ‘get_system_time’ is not a member of ‘uhd::time_spec_t’.  It seems that UHD removed the get_system_time function from time_spec_t within the last few months. From https://github.com/gnuradio/gnuradio/issues/1706 

Here is the compile result.
[  2%] Automatic MOC for target gnuradio-ettus
[  4%] Built target doxygen_target
[  4%] Built target pygen_apps_9a6dd
[  8%] Built target _ettus_swig_doc_tag
[ 12%] Built target pygen_python_51c51
[ 19%] Built target pygen_python_rfnoc_modtool_262c4
[ 19%] Built target pygen_python_utils_0a234
[ 19%] Built target gnuradio-ettus_autogen
[ 23%] Built target ettus_swig_swig_doc
[ 27%] Built target _ettus_swig_swig_tag
Scanning dependencies of target gnuradio-ettus
[ 38%] Built target ettus_swig_swig_2d0df
[ 44%] Built target pygen_swig_b475a
[ 46%] Building CXX object lib/CMakeFiles/gnuradio-ettus.dir/device3.cc.o
[ 48%] Linking CXX shared library libgnuradio-ettus.so
[ 80%] Built target gnuradio-ettus
[ 82%] Automatic MOC for target test-ettus
[ 85%] Building CXX object swig/CMakeFiles/_ettus_swig.dir/ettus_swigPYTHON_wrap.cxx.o
[ 85%] Built target test-ettus_autogen
[ 87%] Linking CXX executable test-ettus
[ 93%] Built target test-ettus
/home/wangy0k/Downloads/gr-ettus/gr-ettus/build/swig/ettus_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_time_spec_t_get_system_time(PyObject*, PyObject*)’:
/home/wangy0k/Downloads/gr-ettus/gr-ettus/build/swig/ettus_swigPYTHON_wrap.cxx:17777:16: error: ‘get_system_time’ is not a member of ‘uhd::time_spec_t’
       result = uhd::time_spec_t::get_system_time();
                ^
swig/CMakeFiles/_ettus_swig.dir/build.make:70: recipe for target 'swig/CMakeFiles/_ettus_swig.dir/ettus_swigPYTHON_wrap.cxx.o' failed
make[2]: *** [swig/CMakeFiles/_ettus_swig.dir/ettus_swigPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:450: recipe for target 'swig/CMakeFiles/_ettus_swig.dir/all' failed
make[1]: *** [swig/CMakeFiles/_ettus_swig.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by snguyen97** [comment]
Yes I got the same issue too. Not quite sure how to resolve this

**Comment by primercuervo** [comment]
@yuanhaowang1213 have you tried the recommended solution from the issue that you are referencing? 
As said there, the get_system_time function was removed from time_spec_t recently and it is probably that you are still using the old version of the headers. This can be solved by deleting the gr-ettus build directory and then having a clean rebuild of your software.

Please let us know if the issue persists after that.

**Comment by yuanhaowang1213** [comment]
@primercuervo Yes, you are right. It works for me. Thank you.

**Comment by yuanhaowang1213** [comment]
@snguyen97 You can try the method @primercuervo mentioned.

**Comment by yuanhaowang1213** [comment]
@snguyen97 Do u have gnuradio? I installed gnuradio firstly, and then there will be a gr-uhd file in the build directory. And then I installed the gr-ettus with the gr-uhd file deleted.
So, my installment sequence is uhd, gnuradio, gr-ettus. And all are installed from github.
