### ISSUE TITLE
GUI of uhd_image_builder.py not correctly updated after "Import from GRC"

### ISSUE THREAD

**Issue by MungerNI** [EttusResearch/gr-ettus#30]
The uhd_image_builder GUI does not correctly update the Block count and the uhd_image_builder command after importing required blocks from a GRC. This is a cosmetic issue. As soon as any button is clicked, the gui is updated correctly. Also hitting the "Generate .bit file" button works correctly.

![grafik](https://user-images.githubusercontent.com/42603138/47807408-350fde80-dcf9-11e8-887b-e177f08de76b.png)

**Comment by mbr0wn** [comment]
Fixed via https://github.com/EttusResearch/fpga/pull/34.
