### ISSUE TITLE
Handle lowercase hex values in NoC ID

### ISSUE THREAD

**Issue by mattpopovich** [EttusResearch/gr-ettus#36]
Any reason why we can't call `.upper()` [here](https://github.com/EttusResearch/gr-ettus/blob/c3b6a3ef6a3fadaf13fac0d21f7f5959e2c0a2b3/python/rfnoc_modtool/util_functions.py#L152) to avoid getting the error [here](https://github.com/EttusResearch/gr-ettus/blob/c3b6a3ef6a3fadaf13fac0d21f7f5959e2c0a2b3/python/rfnoc_modtool/modtool_add.py#L117) if the user uses lowercase hex values? 
Or add lowercase a-f to [the regex](https://github.com/EttusResearch/gr-ettus/blob/c3b6a3ef6a3fadaf13fac0d21f7f5959e2c0a2b3/python/rfnoc_modtool/modtool_add.py#L116)?

**Comment by mbr0wn** [comment]
No reason. It's a good point. I'll add `a-f`.
