### ISSUE TITLE
port to GNU radio 3.8

### ISSUE THREAD

**Issue by erikheinz** [EttusResearch/gr-ettus#37]
Hi,
are there any efforts yet to port gr-ettus to GNU radio 2.8? 
Would it be straightforward or are there any serious obstacles expected?

Wishing to try out the RFNoC blocks (and for some reason bound to the GIT master branch  of GNU radio) I have made an attempt myself - with limited success. I was able to compile and install most of gr-ettus. 
Of course the yml definitions of the blocks are missing, and automatic conversin of the xml files did not work, so I created one yml file by hand (the DmaFIFO block). The block shows up in grc and I could get rid of most error messages. 
The in- and out-ports, however, are  still are complaining about  'Domain key "rfnoc" is not registered' and I cannot connect anythin to this block.

Any ideas? How do I register the rfnoc Domain?

Thank you, and best regards,
Erik

**Comment by marcusmueller** [comment]
with the maint-3.8 branch functional, I think this could be closed. @mbr0wn ?

**Comment by mbr0wn** [comment]
Yes, specifically, https://github.com/EttusResearch/gr-ettus/tree/maint-3.8-uhd4.0.
