### ISSUE TITLE
CMakeLists.txt generated by rfnocmodtool points to non-existent fpga-src directory

### ISSUE THREAD

**Issue by robincoxe** [EttusResearch/gr-ettus#38]
Line 250 of `gr-ettus/python/rfnoc_modtool/rfnoc-newmod/CMakeLists.txt` has a bug:

`COMMAND source ${FPGA}/usrp3/top/e300/setupenv.sh && make -C rfnoc/testbenches/${name} ${SIM} FPGA_TOP_DIR=${FPGA}`

e300 is now e3xx in the fpga repo, so this step causes make noc_block_[name_of_your_block]_tb to fail.  

Also might be worth changing `rfnoc/testbenches/${name} `to an absolute path-- `${CMAKE_SOURCE_DIR}/rfnoc/testbenches/${name}`

**Comment by robincoxe** [comment]
I should also add that on Ubuntu, I had to remove the `source` before invoking setupenv.sh for it not to puke.   Source works from the command line, oddly.  Shell is set to bash so Vivado doesn't complain.

**Comment by primercuervo** [comment]
@mbr0wn This can be closed

**Comment by natetemple** [comment]
Thanks for the bug report @robincoxe, and thanks for the PR @primercuervo !
