### ISSUE TITLE
Burst mode support in gr-ettus radios

### ISSUE THREAD

**Issue by ljxangus** [EttusResearch/gr-ettus#40]
I would like to ask whether the `gr-ettus` radio block supports burst mode or not? I compare the code of the radio block in `gr-ettus` with the `usrp_sink` in GNURadio repo. It seems that `rfnoc_block_impl.cc` does not read the stream-tags in the samples.

**Comment by mbr0wn** [comment]
In `maint-3.8-uhd4.0` EOB tags are set as expected, as in the latest additions to gr-uhd.

In `maint-3.7` and `maint-3.8`, this is not true. We have no roadmap items to fix that.
