### ISSUE TITLE
gr-ettus installation fatal error

### ISSUE THREAD

**Issue by viktorivan** [EttusResearch/gr-ettus#43]
Hi, I am installing rfnoc with gnuradio 3.7 with pybombs

gr-ettus:
    gitbranch: master
    forcebuild: true

I have the following error.

[  2%] Automatic MOC for target gnuradio-ettus
[  2%] Built target gnuradio-ettus_autogen
[  4%] Building CXX object lib/CMakeFiles/gnuradio-ettus.dir/device3.cc.o
In file included from /home/ivan/rfnoc/src/gr-ettus/lib/device3.cc:27:0:
/home/ivan/rfnoc/src/gr-ettus/include/ettus/device3.h:30:10: fatal error: uhd/device3.hpp: No such file or directory
 #include <uhd/device3.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
lib/CMakeFiles/gnuradio-ettus.dir/build.make:72: recipe for target 'lib/CMakeFiles/gnuradio-ettus.dir/device3.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-ettus.dir/device3.cc.o] Error 1
CMakeFiles/Makefile2:139: recipe for target 'lib/CMakeFiles/gnuradio-ettus.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-ettus.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
[ERROR] Build failed. See output above for error messages.
[ERROR] Problem occurred while building package gr-ettus:
Build failed.
[ERROR] Error installing package gr-ettus. Aborting.

Regards

**Comment by mgarrett1955** [comment]
Im having this same issue installing gr-ettus on a fresh UHD 4 and GNURADIO 3.8 installation on Ubuntu 18.4. 
Gnuradio and UHD seem to be full functional.

**Comment by mbr0wn** [comment]
None of these branches work with UHD 4. Either use `maint-3.8-uhd4.0` or use UHD 3.x with these branches.
