### ISSUE TITLE
Build failing when using master-next

### ISSUE THREAD

**Issue by MichaelFay** [EttusResearch/gr-ettus#44]
When building master-next, gr-ettus is failing to build due to 

![Screen Shot 2020-02-17 at 6 28 04 PM](https://user-images.githubusercontent.com/6434547/74693868-4d885e80-51b3-11ea-8964-123d44bba67a.png)

OS: Ubuntu 18.04
GNU Radio: 3.8.0.0 & 3.8.1.0-rc1
UHD: master

**Comment by michaelld** [comment]
That graphic is very difficult to read. Can you cut/paste it in instead?

**Comment by MichaelFay** [comment]
/usr/local/src/gr-ettus/lib/rfnoc_rx_streamer_impl.cc: In constructor 'gr::ettus::rfnoc_rx_streamer_impl::rfnoc_rx_streamer_impl(gr::ettus::rfnoc_graph::sptr, size_t, const uhd::stream_args_t&, size_t, bool)':
/usr/local/src/gr-ettus/lib/rfnoc_rx_streamer_impl.cc:58:71: error: no matching function for call to 'dynamic_pointer_cast<uhd::rfnoc::node_t>(uhd::rx_streamer::sptr&)'
           boost::dynamic_pointer_cast<::uhd::rfnoc::node_t>(d_streamer)->get_unique_id()),

**Comment by mbr0wn** [comment]
`master-next` is now replaced by native gr-uhd support. If you build HEAD of GNU Radio master, you'll get this feature.
