### ISSUE TITLE
Cannot find or link against gr-ettus with Gnuradio 3.8?

### ISSUE THREAD

**Issue by ejk43** [EttusResearch/gr-ettus#46]
I had some problems finding and linking against gr-ettus when upgrading rfnoc OOT modules to GR 3.8. I believe this is related to Gnuradio's cmake update (https://github.com/gnuradio/gnuradio/issues/2429 -- which does not appear to be resolved??), but I'm really not clear what the fix should be.

I tried several approaches:

1. Using the "legacy" `find_package(ettus)` command in CMakeLists -- this was the general way to handle finding gr-ettus with  gnuradio 3.7

Instead I get a cmake configure error

```
--   No package 'ettus' found
CMake Error at /usr/local/lib/cmake/ettus/ettusConfig.cmake:41 (include):
  include could not find load file:
    /usr/local/lib/cmake/ettus/ettusTarget.cmake
```

I think this traces back to the ettusConfig.cmake provided by gr-ettus pointing to ettusTarget.cmake -- but this file has now changed names to gnuradio-ettusTargets.cmake. One possible answer might be the solution thanks to @yaaseen-dev here: https://github.com/yaaseen-dev/gr-ettus/commit/cb6c79f89fa5e35db1eff02a681140a657158a5d#diff-179e4ad3bfd5e35f054cf090710afd42R27

2. I also tried: `find_package(gnuradio-ettus)`

This seems more promising, since GR_LIBRARY_FOO seems to install gnuradio-ettus cmake files into the lib/cmake/ettus install location. This fails in cmake configure with the following error:

```
CMake Error at gr-theseus/CMakeLists.txt:84 (find_package):
  By not providing "Findgnuradio-ettus.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "gnuradio-ettus", but CMake did not find one.

  Could not find a package configuration file provided by "gnuradio-ettus"
  with any of the following names:

    gnuradio-ettusConfig.cmake
    gnuradio-ettus-config.cmake

  Add the installation prefix of "gnuradio-ettus" to CMAKE_PREFIX_PATH or set
  "gnuradio-ettus_DIR" to a directory containing one of the above files.  If
  "gnuradio-ettus" provides a separate development package or SDK, be sure it
  has been installed.
```

Interestingly, if I change the GR_CMAKE_DIR *inside gr-ettus* to point to ${CMAKE_MODULES_DIR)/gnuradio-ettus (https://github.com/EttusResearch/gr-ettus/blob/b69260655e974786ea6e611bd91ab578b13ec72a/CMakeLists.txt#L69), then the gnuradio-ettus cmake modules get installed to lib/cmake/gnuradio-ettus. Then, in my OOT module, calling `find_package(gnuradio-ettus)` finds gr-ettus, and `target_link_libraries(<my-library> gnuradio-ettus)` links successfully.

So: Is this right? Am I missing something obvious here? 

Has anyone else ported rfnoc repos to gnuradio 3.8??

**Comment by ejk43** [comment]
As another update, I've found that installation into the root filesystem or an install prefix can just call `target_link_libraries(<my-library> gnuradio-ettus)` successfully...

So I've been able to get libraries to build correctly in a dockerfile: https://gitlab.com/theseus-cores/theseus-docker/-/blob/master/gnuradio-3.8/Dockerfile

However I still run into problems calling `find_package(ettus)` or `find_package(gnuradio-ettus)`

**Comment by mbr0wn** [comment]
I'm pretty sure that 29382c49ff9045cd39b1395f254007c0ae2c5535 fixed this issue. I just ran it and it worked fine.
