### ISSUE TITLE
Impossible to have make() parameters w/ default values before non-defaulting params

### ISSUE THREAD

**Issue by marcusmueller** [EttusResearch/gr-ettus#5]
https://github.com/EttusResearch/gr-ettus/blob/radio-redo/python/rfnoc_modtool/templates.py#L388 :

```
…
      static sptr make(
#if $blocktype == 'rfnoc'
#if $arglist
        $arglist,
#end if
        const gr::ettus::device3::sptr &dev,
…
```

this should have been stripped of default arguments, too, like elsewhere in the templates. But since `make` _is_ the public interface to the block, not having default arguments here does make these useless (aside from putting them in as default values in the GRC .xml).

**Comment by mbr0wn** [comment]
@primercuervo Want to take a look at this?

**Comment by primercuervo** [comment]
9ff4fefa487537d819b886e56665d2be1ee697e7
