### ISSUE TITLE
Error in compiling gr-ettus  No rule to make target

### ISSUE THREAD

**Issue by stackprogramer** [EttusResearch/gr-ettus#58]
Error in compiling........How can solve it......

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/liborc-0.4.so', needed by 'lib/libgnuradio-ettus.so.v3.8-compat-xxx-xunknown'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:289: lib/CMakeFiles/gnuradio-ettus.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by a-andre** [comment]
Looks like package `liborc-0.4-dev` is missing.

**Comment by stackprogramer** [comment]
+1 

thanks my problemis solved with......
sudo apt-get update
sudo apt-get install liborc-0.4-dev
