### ISSUE TITLE
RFNoC: make.py path is inconvenient to access

### ISSUE THREAD

**Issue by ttsou** [EttusResearch/gr-ettus#6]
In the current [RFNoC getting started](https://kb.ettus.com/Getting_Started_with_RFNoC_Development) guide, when building images the user is required to specify the full or relative path to 'make.py', which is clunky and involves a lot of typing.

For example,

```
$  {INSTALL_PREFIX}/src/uhd-fpga/usrp3_rfnoc/tools/scripts/make.py null_source_sink siggen
```

A more convenient approach to calling make.py is desirable.

**Comment by mbr0wn** [comment]
make.py is no more. uhd_image_builder is it!
