### ISSUE TITLE
ettus_rfnoc_graph.block.yml does not configure time and clock sources

### ISSUE THREAD

**Issue by Zlika** [EttusResearch/gr-ettus#62]
The "RFNoC graph block" described by ettus_rfnoc_graph.block.yml allows the user to configure the time source and the clock source for each Mboard. However, these configuration items are not used in the "templates" section. The "templates" section should call the set_time_source() and set_clock_source() methods to configure the rfnoc graph block as requested by the user.

**Comment by mbr0wn** [comment]
Fixed here via b7bc02f49352e589412287ae632e8bb940eabeec, on gr-uhd via https://github.com/gnuradio/gnuradio/pull/6349.
