### ISSUE TITLE
version problem of GNURadio and UHD and RFNoC

### ISSUE THREAD

**Issue by 2444616578** [EttusResearch/gr-ettus#65]
I've tried several version combinations of UHD , GNURadio and RFNoC(gr_ettus). 

When I am using UHD3.15+GNURadio3.8   rfnocmodtool in gr_ettus is for GNURadio 3.7 , so this conbanion is failed

When I am using GNURadio 3.8 and UHD4.0 the gr_ettus can not be cmaked. 

Eventually, I successfully use rfmocmodtool with the conbanion of UHD3.15+GNURadio3.7, and program FPGA in X310. but I had to rewrite my gr_modtool OOT block for low version 3.7 of GNURadio. 

The description of my failure experience may be inaccurate due to the time passed， but I hope Ettus can provide a correct gr_ettus software package for deverse combanion of UHD and GNURadio. and determine rfnocmodtool can run successfully.

I think my experience could  be helpful.

By the way, I download ZIP of UHD, GNURADIO and ge_ettus  form github because of my bad webwork, and I didn't use the git tool.

**Comment by RFNOD** [comment]
Hi @2444616578 Is this on ubuntu 20.04 or what OS are you using? I was able to get GR3.8 to work with UHD4.0 - 4.1.0.6 by compiling UHD from source. That has allowed me to compile gr-ettus from source after I have GR installed. I also compile GR from source as I have to for some work I do while using GR. I hope that gets you going in the right direction.

**Comment by 2444616578** [comment]
> 

Thank you for your advice.
I am using ubantu 18.04, this can be the reason why I failed several times. 
I will take your advice an try to change my ubantu version.
Thank you again at last. @RFNOD

**Comment by mbr0wn** [comment]
You might have been using the wrong branch. UHD 4.x + GR 3.8 is definitely supported by this OOT Module.
